name: Merge Hugging Face Repository

on:
  push:
    branches:
      - main  # Trigger on push to main branch, modify as needed

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.name 'amaye15'
          git config --global user.email 'andrewmayes14@hotmail.com'
          git remote add huggingface https://huggingface.co/datasets/amaye15/Stack-Overflow-Zero-Shot-Classification
          git fetch huggingface

      - name: Merge Hugging Face repository
        run: |
          git checkout -b merge-huggingface
          git merge huggingface/main  # Adjust branch name as necessary
          git push origin merge-huggingface
